// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {slog} from '../models';

export function Debug(arg1:string,arg2:Array<any>):Promise<void>;

export function DebugContext(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<void>;

export function Enabled(arg1:context.Context,arg2:slog.Level):Promise<boolean>;

export function Error(arg1:string,arg2:Array<any>):Promise<void>;

export function ErrorContext(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<void>;

export function Handler():Promise<slog.Handler>;

export function Info(arg1:string,arg2:Array<any>):Promise<void>;

export function InfoContext(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<void>;

export function Log(arg1:context.Context,arg2:slog.Level,arg3:string,arg4:Array<any>):Promise<void>;

export function LogAttrs(arg1:context.Context,arg2:slog.Level,arg3:string,arg4:Array<slog.Attr>):Promise<void>;

export function Warn(arg1:string,arg2:Array<any>):Promise<void>;

export function WarnContext(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<void>;

export function With(arg1:Array<any>):Promise<slog.Logger>;

export function WithGroup(arg1:string):Promise<slog.Logger>;
