// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Debug(arg1, arg2) {
  return window['go']['slog']['Logger']['Debug'](arg1, arg2);
}

export function DebugContext(arg1, arg2, arg3) {
  return window['go']['slog']['Logger']['DebugContext'](arg1, arg2, arg3);
}

export function Enabled(arg1, arg2) {
  return window['go']['slog']['Logger']['Enabled'](arg1, arg2);
}

export function Error(arg1, arg2) {
  return window['go']['slog']['Logger']['Error'](arg1, arg2);
}

export function ErrorContext(arg1, arg2, arg3) {
  return window['go']['slog']['Logger']['ErrorContext'](arg1, arg2, arg3);
}

export function Handler() {
  return window['go']['slog']['Logger']['Handler']();
}

export function Info(arg1, arg2) {
  return window['go']['slog']['Logger']['Info'](arg1, arg2);
}

export function InfoContext(arg1, arg2, arg3) {
  return window['go']['slog']['Logger']['InfoContext'](arg1, arg2, arg3);
}

export function Log(arg1, arg2, arg3, arg4) {
  return window['go']['slog']['Logger']['Log'](arg1, arg2, arg3, arg4);
}

export function LogAttrs(arg1, arg2, arg3, arg4) {
  return window['go']['slog']['Logger']['LogAttrs'](arg1, arg2, arg3, arg4);
}

export function Warn(arg1, arg2) {
  return window['go']['slog']['Logger']['Warn'](arg1, arg2);
}

export function WarnContext(arg1, arg2, arg3) {
  return window['go']['slog']['Logger']['WarnContext'](arg1, arg2, arg3);
}

export function With(arg1) {
  return window['go']['slog']['Logger']['With'](arg1);
}

export function WithGroup(arg1) {
  return window['go']['slog']['Logger']['WithGroup'](arg1);
}
