// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';
import {embed} from '../models';
import {models} from '../models';

export function Init(arg1:utils.CustomLogger,arg2:embed.FS):Promise<models.App>;

export function OpenSaveFileDialog():Promise<string>;

export function PromptUserSelect(arg1:models.PromptSelectConfig):Promise<string>;

export function SelectMultipleFiles(arg1:string,arg2:string):Promise<Array<string>>;
