// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenSaveFileDialog() {
  return window['go']['models']['App']['OpenSaveFileDialog']();
}

export function PromptUserSelect(arg1) {
  return window['go']['models']['App']['PromptUserSelect'](arg1);
}

export function SelectMultipleFiles(arg1, arg2) {
  return window['go']['models']['App']['SelectMultipleFiles'](arg1, arg2);
}
