// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function OpenSaveFileDialog():Promise<string>;

export function PromptUserSelect(arg1:models.PromptSelectConfig):Promise<string>;

export function SearchFileInUserDir(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SelectMultipleFiles(arg1:string,arg2:string):Promise<Array<string>>;
