// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Debug(arg1, arg2) {
  return window['go']['models']['Logger']['Debug'](arg1, arg2);
}

export function Error(arg1, arg2) {
  return window['go']['models']['Logger']['Error'](arg1, arg2);
}

export function Info(arg1, arg2) {
  return window['go']['models']['Logger']['Info'](arg1, arg2);
}

export function Warn(arg1, arg2) {
  return window['go']['models']['Logger']['Warn'](arg1, arg2);
}
