// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressFile(arg1, arg2) {
  return window['go']['models']['PdfHandler']['CompressFile'](arg1, arg2);
}

export function ConvertImageToPdf(arg1, arg2) {
  return window['go']['models']['PdfHandler']['ConvertImageToPdf'](arg1, arg2);
}

export function MergePdfFiles(arg1, arg2) {
  return window['go']['models']['PdfHandler']['MergePdfFiles'](arg1, arg2);
}

export function OptimizePdfFile(arg1) {
  return window['go']['models']['PdfHandler']['OptimizePdfFile'](arg1);
}

export function ResizePdfFileToA4(arg1) {
  return window['go']['models']['PdfHandler']['ResizePdfFileToA4'](arg1);
}
