// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressFile(arg1, arg2) {
  return window['go']['models']['PdfService']['CompressFile'](arg1, arg2);
}

export function ConvertImageToPdf(arg1, arg2) {
  return window['go']['models']['PdfService']['ConvertImageToPdf'](arg1, arg2);
}

export function CreateTempFilesFromUpload(arg1) {
  return window['go']['models']['PdfService']['CreateTempFilesFromUpload'](arg1);
}

export function Init(arg1, arg2) {
  return window['go']['models']['PdfService']['Init'](arg1, arg2);
}

export function MergePdfFiles(arg1, arg2, arg3) {
  return window['go']['models']['PdfService']['MergePdfFiles'](arg1, arg2, arg3);
}

export function ResizePdfFileToA4(arg1) {
  return window['go']['models']['PdfService']['ResizePdfFileToA4'](arg1);
}
