// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Init(arg1) {
  return window['go']['models']['UserPrompter']['Init'](arg1);
}

export function OpenOutputDir() {
  return window['go']['models']['UserPrompter']['OpenOutputDir']();
}

export function OpenSaveFileDialog() {
  return window['go']['models']['UserPrompter']['OpenSaveFileDialog']();
}

export function PromptUserSelect(arg1) {
  return window['go']['models']['UserPrompter']['PromptUserSelect'](arg1);
}

export function SearchFileInUserDir(arg1, arg2, arg3) {
  return window['go']['models']['UserPrompter']['SearchFileInUserDir'](arg1, arg2, arg3);
}

export function SelectMultipleFiles(arg1, arg2) {
  return window['go']['models']['UserPrompter']['SelectMultipleFiles'](arg1, arg2);
}
