// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {slog} from '../models';

export function Close():Promise<void>;

export function Error(arg1:string,arg2:Array<slog.Attr>):Promise<void>;

export function Info(arg1:string,arg2:Array<slog.Attr>):Promise<void>;
