// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['utils']['CustomLogger']['Close']();
}

export function Debug(arg1, arg2) {
  return window['go']['utils']['CustomLogger']['Debug'](arg1, arg2);
}

export function Error(arg1, arg2) {
  return window['go']['utils']['CustomLogger']['Error'](arg1, arg2);
}

export function Info(arg1, arg2) {
  return window['go']['utils']['CustomLogger']['Info'](arg1, arg2);
}

export function Warn(arg1, arg2) {
  return window['go']['utils']['CustomLogger']['Warn'](arg1, arg2);
}
