// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseCompressionMode():Promise<string>;

export function OpenSaveFileDialog():Promise<string>;

export function SelectMultipleFiles(arg1:string,arg2:string):Promise<Array<string>>;
