// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressPdfFile(arg1) {
  return window['go']['main']['App']['CompressPdfFile'](arg1);
}

export function ConvertImageToPdf(arg1) {
  return window['go']['main']['App']['ConvertImageToPdf'](arg1);
}

export function MergePdfFiles(arg1) {
  return window['go']['main']['App']['MergePdfFiles'](arg1);
}

export function SelectMultipleFiles(arg1, arg2) {
  return window['go']['main']['App']['SelectMultipleFiles'](arg1, arg2);
}
