// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseCompressionMode() {
  return window['go']['main']['App']['ChooseCompressionMode']();
}

export function OpenSaveFileDialog() {
  return window['go']['main']['App']['OpenSaveFileDialog']();
}

export function SelectMultipleFiles(arg1, arg2) {
  return window['go']['main']['App']['SelectMultipleFiles'](arg1, arg2);
}
