// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressFile(arg1) {
  return window['go']['main']['PdfTools']['CompressFile'](arg1);
}

export function CompressPdfFile(arg1) {
  return window['go']['main']['PdfTools']['CompressPdfFile'](arg1);
}

export function ConvertImageToPdf(arg1) {
  return window['go']['main']['PdfTools']['ConvertImageToPdf'](arg1);
}

export function MergePdfFiles(arg1, arg2) {
  return window['go']['main']['PdfTools']['MergePdfFiles'](arg1, arg2);
}
