// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressFileExtreme(arg1:string):Promise<boolean>;

export function CompressOnePageFileExtreme(arg1:string,arg2:string):Promise<boolean>;

export function ConvertImageToPdf(arg1:string,arg2:Array<string>):Promise<boolean>;

export function MergePdfFiles(arg1:string,arg2:Array<string>):Promise<boolean>;

export function OptimizePdfFile(arg1:string):Promise<void>;
