// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressFile(arg1:string):Promise<void>;

export function ConvertImageToPdf(arg1:string):Promise<void>;

export function MergePdfFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function OptimizePdfFile(arg1:string):Promise<void>;
