// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressFile(arg1, arg2) {
  return window['go']['main']['PdfUtils']['CompressFile'](arg1, arg2);
}

export function ConvertImageToPdf(arg1) {
  return window['go']['main']['PdfUtils']['ConvertImageToPdf'](arg1);
}

export function MergePdfFiles(arg1, arg2) {
  return window['go']['main']['PdfUtils']['MergePdfFiles'](arg1, arg2);
}

export function OptimizePdfFile(arg1) {
  return window['go']['main']['PdfUtils']['OptimizePdfFile'](arg1);
}
